spring:
  application:
    name: microservice-calculation

server:
  port: ${PORT:9001}

config-cache:
  time-expire: 30
  maximum-size: 1
  cache-config-name: calculate
  cache-config-key: UIDDZILQ

external-request:
  #microservice-percentage: ${USERS_URL:http://host.docker.internal:8001/api/v1}
  microservice-percentage: ${USERS_URL:http://localhost:9003/api/v1}
  microservice-callhistoy: ${USERS_URL:http://localhost:9002/api/v1}

logging:
  file:
    path: /app/logs
